# Generated by Django 6.1.1 on 2026-10-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_article_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Нове"),
                            ("in_progress", "У процесі"),
                            ("done", "Готово"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Стаття",
                "verbose_name_plural": "Статті",
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["created_at"], name="polls_artic_created_6597a6_idx"
            ),
        ),
    ]
